### ISSUE TITLE
unable to get any result by running texture shape image that is available on docker hub by you

### ISSUE THREAD

**Issue by FaRe3** [rgeirhos/texture-vs-shape#13]
After running the image , an empty work folders appeared.I dont have any idea how to get any results just by running the docker image.Please help me with that

**Comment by FaRe3** [comment]
work folder in Jupyter notebook*

**Comment by rgeirhos** [comment]
Hey there. Could you specify
a) which result you're aiming for and
b) after running the image, which steps (if any) did you do?

**Comment by FaRe3** [comment]
i thought if i run the image it will show me the analysis that is done. the
pdf files with the graphs and all.but all i got was empty jupyter notebook
with and an empty work folder. What should i do after running the image. I
m trying to get results that are mentioned in the paper.Is it possible just
with the docker image you provided in docker hub.

I also wanted your help in few more things. I have been trying to run data
analysis part  but not able to get confusion matrix pdf . also where did
you connect the .py file with R script.

Thank you for your response.

**Comment by FaRe3** [comment]
I thought if i run the image it will show me the analysis that is done. the
pdf files with the graphs and all but all i got was empty jupyter notebook
with  an empty work folder. What should i do after running the image. I m
trying to get results that are mentioned in the paper.Is it possible just
with the docker image you provided in docker hub.

I also wanted your help in few more things. I have been trying to run data
analysis part  but not able to get confusion matrix pdf . also where did
you connect the .py file with R script.

Thank you for your response.

**Comment by FaRe3** [comment]
Hey there! I was hoping if i can get help with my issue

**Comment by rgeirhos** [comment]
Ok so running the docker image will enable you to generate Stylized-ImageNet without the need to install all sorts of libraries beforehand. The docker image has no connection to the data analysis part.

Concerning the "confusion matrix pdf" mentioned by you, I am not entirely sure I understand ... the paper does not include a confusion matrix.

Furthermore, the R script is not connected to any .py files.

In order to reproduce the plots from the paper, you will need to run the following R script: https://github.com/rgeirhos/texture-vs-shape/blob/master/data-analysis/data-analysis.R
