### ISSUE TITLE
A query : Can you explain what is different in shape-resnet?

### ISSUE THREAD

**Issue by jadevaibhav** [rgeirhos/texture-vs-shape#18]
Hi Robert,

This paper has been a great read and peeking under the curtain of black-box CNNs. Really thought provoking work. I have one doubt about shape-resnet model you have referred to in table 1 and table 2. It says in the paper:
_Training jointly on SIN and IN with fine-tuning on IN. We refer to this model as Shape-ResNet._
Although in table 2 shows comparison of vanilla and shape resnet both with SIN+IN training. Can you clarify the differences of vanilla and shape-resnet?

Thanks in advance.

**Comment by rgeirhos** [comment]
Vanilla ResNet: standard ResNet-50 trained on ImageNet
the other three networks from table 2 all have been exposed to different degrees of stylized data during training. I wouldn't worry too much about the name "Shape-ResNet" since different degrees of stylized training are helpful for different purposes: in order to get the best ImageNet performance, fine-tuning on ImageNet was best but then the model doesn't have a huge shape bias anymore (see README), etc. 
Does this answer your question?

**Comment by jadevaibhav** [comment]
Sure, this helps, thanks!
