### ISSUE TITLE
Texture dataset (48 images)

### ISSUE THREAD

**Issue by felixlaumon** [rgeirhos/texture-vs-shape#19]
From Section 2.2. of the paper

> 48 natural colour images of textures (3 per category). Typically the textures consist of full-width patches of an animal (e.g.  skin or fur) or, in particular for man-made objects, of images with many repetitions of the same objects (e.g. many bottles next to each other, see Figure 7 in the Appendix).

I notice that the style-transferred images are in `stimuli/style-transfer-preprocessed-512` folder but not the original texture / style images. I understand that they might come from ImageNet so there will be licensing issue. Would it be possible to publish at least the IDs of the texture you used?

Thank you!

**Comment by rgeirhos** [comment]
The original images were manually collected; they are not part of ImageNet due to different requirements (e.g. for the original images we needed to make sure that the background was white in order to avoid introducing additional confounding factors).
Unfortunately, I cannot share these images (see https://github.com/rgeirhos/texture-vs-shape#in-addition-to-the-cue-conflict-stimuli-can-you-share-the-stimuli-for-the-texture-experiment--the-original-experiment--).
