### ISSUE TITLE
raw stimuli

### ISSUE THREAD

**Issue by jurschreuder** [rgeirhos/texture-vs-shape#2]
Hi Robert Geirhos,

I am currently creating an experiment where the effect of different image transformations on both human and CNN performance is compared.
I had to pick some categories out of all 1000 ImageNet categories, and thought you have made a nice selection that I can use as kind of a standard also used in other research.
That way I can also include the stimuli you have already created, and add my own stimuli.
The problem I am facing now is that you did not include the base images in the stimuli folder.
So to add new transformations of the stimuli I will have to find other examples than the ones used for style transfer and contours.
For me it would be of great help if also the base stimuli, without the style altered, were included in the stimuli folder, so I can base other transformations directly on those stimuli.

I will obviously reference your research in any publications using the style transfer and contour images provided in this repository.

Kind Regards!

Jurriaan Schreuder, PhD student at the University of Amsterdam

**Comment by rgeirhos** [comment]
Hi Jurriaan,
Thanks for reaching out. Sounds interesting, please let me know once you have results! ;)

Depending on your experiments, I think two different options may be worth considering:

A) if you're just looking for a selection of ImageNet classes, I'd like to point you to the  [16-class-ImageNet selection](https://github.com/rgeirhos/generalisation-humans-DNNs) which includes a large number of images per class, and is also a published dataset. This might be preferable over using just the 160 images of the texture-vs-shape paper, which might be too small for some experiments as it contains just 10 images per class.

B) if you think the 160 images will be just fine, there's a bit of a problem: I would've loved to publish this dataset on github as well but I'm prevented from doing so due to image rights / attribution issues. However, please reach out to me via email in this case and I'll see what I can do (robert.geirhos@bethgelab.org).

Hope this helps!
